const glow = document.querySelector('.cursor-glow');
window.addEventListener('pointermove', (e) => {
  glow.style.left = e.clientX + 'px';
  glow.style.top = e.clientY + 'px';
});

const workSection = document.querySelector('#work');
if (workSection) {
  const process = document.createElement('section');
  process.className = 'process section';
  process.innerHTML = `<div class="process-top"><p class="section-label">02 / Как я работаю</p><p class="process-note">От первой идеи до готового визуального решения</p></div><div class="process-grid"><article class="process-step"><span>01</span><div><h3>Погружаюсь</h3><p>Разбираю задачу, материал и аудиторию, чтобы понять, что действительно важно.</p></div><b>↘</b></article><article class="process-step"><span>02</span><div><h3>Структурирую</h3><p>Выстраиваю логику, иерархию и акценты — чтобы информацию было легко воспринимать.</p></div><b>↘</b></article><article class="process-step"><span>03</span><div><h3>Упаковываю</h3><p>Создаю визуальную концепцию и дизайн, который поддерживает смысл, а не спорит с ним.</p></div><b>↘</b></article><article class="process-step"><span>04</span><div><h3>Передаю результат</h3><p>Собираю финальный материал и привожу его к виду, с которым можно сразу работать.</p></div><b>↗</b></article></div>`;
  workSection.parentNode.insertBefore(process, workSection);
}

const reveal = new IntersectionObserver((entries) => {
  entries.forEach(entry => { if (entry.isIntersecting) entry.target.classList.add('is-visible'); });
}, { threshold: 0.08 });

document.querySelectorAll('.project, .service, .intro-grid, .about-grid, .contact-row, .contact-heading, .contact-form-wrap, .process-grid, .process-top').forEach(el => reveal.observe(el));

const style = document.createElement('style');
style.textContent = `
.project,.service,.intro-grid,.about-grid,.contact-row,.contact-heading,.contact-form-wrap,.process-grid,.process-top{opacity:0;transform:translateY(28px);transition:opacity .8s ease,transform .8s ease}.is-visible{opacity:1;transform:none}
.process{background:#f4f1eb;border-top:1px solid #111;border-bottom:1px solid #111}.process-top{display:flex;justify-content:space-between;align-items:end;gap:30px}.process-top .section-label{margin-bottom:0}.process-note{font-size:12px;opacity:.5;margin:0}.process-grid{border-top:1px solid #111}.process-step{display:grid;grid-template-columns:72px 1fr 58px;gap:28px;align-items:start;padding:34px 0;border-bottom:1px solid #111;position:relative;transition:padding .4s cubic-bezier(.2,.7,.2,1),background .4s ease}.process-step:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:#d6ff36;transform:scaleY(0);transform-origin:center;transition:transform .4s cubic-bezier(.2,.7,.2,1)}.process-step:nth-child(2):before,.process-step:nth-child(4):before{background:#b9a6ff}.process-step:hover{padding-left:22px;padding-right:12px;background:rgba(214,255,54,.13)}.process-step:hover:before{transform:scaleY(1)}.process-step>span{font-size:11px;letter-spacing:.14em;font-weight:800;opacity:.4;padding-top:8px}.process-step h3{font-size:clamp(28px,4vw,58px);line-height:.95;letter-spacing:-.055em;margin:0 0 9px;transition:transform .4s ease}.process-step:hover h3{transform:translateX(7px)}.process-step p{font-size:14px;line-height:1.55;max-width:600px;margin:0;opacity:.55}.process-step b{width:48px;height:48px;border:1px solid rgba(17,17,17,.55);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:18px;font-weight:500;transition:transform .4s ease,background .3s ease,color .3s ease}.process-step:hover b{transform:rotate(-35deg);background:#111;color:#fff}
.service-list{position:relative;overflow:hidden}.service{position:relative;grid-template-columns:72px minmax(280px,1.1fr) minmax(240px,.7fr) 58px;gap:28px;padding:38px 0;transition:padding .45s cubic-bezier(.2,.7,.2,1),background .45s ease}.service:before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:#d6ff36;transform:scaleY(0);transform-origin:center;transition:transform .4s cubic-bezier(.2,.7,.2,1)}.service:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(214,255,54,.11),transparent 55%);opacity:0;pointer-events:none;transition:opacity .45s ease}.service:hover{padding-left:24px;padding-right:18px;background:transparent}.service:hover:before{transform:scaleY(1)}.service:hover:after{opacity:1}.service>span,.service h3,.service p,.service b{position:relative;z-index:1}.service>span{font-size:11px;letter-spacing:.14em;font-weight:800;opacity:.42;align-self:start;padding-top:8px;transition:color .35s ease,opacity .35s ease}.service:hover>span{color:#111;opacity:1}.service h3{font-size:clamp(30px,4.2vw,64px);line-height:.95;letter-spacing:-.06em;margin:0;transition:transform .45s cubic-bezier(.2,.7,.2,1)}.service:hover h3{transform:translateX(8px)}.service p{font-size:14px;line-height:1.55;margin:0;max-width:390px;opacity:.58;transition:opacity .35s ease}.service:hover p{opacity:.9}.service b{width:48px;height:48px;border:1px solid rgba(17,17,17,.65);border-radius:50%;display:flex;align-items:center;justify-content:center;font-size:19px;font-weight:500;transition:transform .45s cubic-bezier(.2,.7,.2,1),background .35s ease,color .35s ease,border-color .35s ease}.service:hover b{transform:rotate(45deg);background:#111;color:#fff;border-color:#111}.service:nth-child(2):before{background:#b9a6ff}.service:nth-child(3):before{background:#d6ff36}.service:nth-child(4):before{background:#b9a6ff}
.contact-heading{display:grid;grid-template-columns:1fr 220px;gap:40px;align-items:end;position:relative;z-index:1}.contact h2{margin-bottom:28px}.contact-lead{max-width:430px;font-size:16px;line-height:1.55;margin:0}.contact-mark{font-size:clamp(42px,5vw,76px);line-height:.82;letter-spacing:-.08em;font-weight:800;opacity:.1;text-align:right;transform:rotate(-8deg)}.contact-form-wrap{margin-top:75px;display:grid;grid-template-columns:.42fr 1fr;gap:7vw;position:relative;z-index:1}.form-intro{padding-top:8px;font-size:13px;line-height:1.55}.form-intro span{font-size:11px;letter-spacing:.16em;font-weight:800;display:block;margin-bottom:22px}.form-intro p{max-width:220px;margin:0}.form-accent{font-size:85px;line-height:1;font-weight:800;margin-top:45px;opacity:.12;transform:rotate(-10deg)}.contact-form{display:grid;grid-template-columns:1fr 1fr;gap:26px 22px}.contact-form label{font-size:11px;font-weight:800;letter-spacing:.08em;text-transform:uppercase;display:flex;flex-direction:column;gap:10px}.contact-form label:nth-child(3),.contact-form label:nth-child(4),.contact-form button,.form-note{grid-column:1 / -1}.contact-form input,.contact-form select,.contact-form textarea{width:100%;border:0;border-bottom:1px solid rgba(17,17,17,.5);border-radius:0;background:transparent;padding:10px 0 13px;font:500 16px Manrope,Arial,sans-serif;color:#111;outline:none;transition:border-color .25s ease,transform .25s ease}.contact-form textarea{resize:vertical;min-height:80px}.contact-form input:focus,.contact-form select:focus,.contact-form textarea:focus{border-bottom-color:#111;transform:translateY(-2px)}.contact-form input::placeholder,.contact-form textarea::placeholder{color:#111;opacity:.42}.contact-form select{appearance:none;cursor:pointer;background-image:linear-gradient(45deg,transparent 50%,#111 50%),linear-gradient(135deg,#111 50%,transparent 50%);background-position:calc(100% - 7px) 17px,calc(100% - 2px) 17px;background-size:5px 5px,5px 5px;background-repeat:no-repeat;padding-right:25px}.contact-form select:invalid{color:rgba(17,17,17,.42)}.contact-form .contact-button{justify-self:start;margin-top:4px;border:0;cursor:pointer;font-family:Manrope,Arial,sans-serif}.contact-form .contact-button span{font-size:18px}.form-note{font-size:11px;opacity:.5;margin:-12px 0 0}
@media(max-width:800px){.process-top{display:block}.process-note{margin-top:-20px;margin-bottom:35px}.process-step{grid-template-columns:35px 1fr 48px;gap:12px;padding:28px 0}.process-step p{grid-column:2}.process-step b{grid-column:3;grid-row:1;width:40px;height:40px}.process-step:hover{padding-left:10px;padding-right:6px}.process-step h3{font-size:30px}.service{grid-template-columns:35px 1fr 48px;gap:12px;padding:28px 0}.service p{grid-column:2;max-width:none}.service b{grid-column:3;grid-row:1;width:40px;height:40px}.service:hover{padding-left:10px;padding-right:6px}.service h3{font-size:30px}.service p{font-size:12px}.contact-heading{grid-template-columns:1fr;gap:20px}.contact-mark{text-align:left;font-size:48px;position:absolute;right:0;top:5px}.contact-form-wrap{grid-template-columns:1fr;gap:35px;margin-top:50px}.form-intro p{max-width:320px}.form-accent{font-size:55px;margin-top:25px}.contact-form{grid-template-columns:1fr;gap:24px}.contact-form label:nth-child(3),.contact-form label:nth-child(4),.contact-form button,.form-note{grid-column:auto}.contact-form .contact-button{width:100%}}
`;
document.head.appendChild(style);

const form = document.querySelector('#contact-form');
if (form) {
  form.addEventListener('submit', async (event) => {
    event.preventDefault();
    const data = new FormData(form);
    const message = ['Новый запрос с сайта Anastasia Galizova','',`Имя: ${data.get('name')}`,`Контакт: ${data.get('contact')}`,`Задача: ${data.get('service')}`,`Проект: ${data.get('message') || 'не указано'}`].join('\n');
    try { await navigator.clipboard.writeText(message); } catch (_) {}
    window.open('https://t.me/galizova_art', '_blank', 'noopener');
    const note = form.querySelector('.form-note');
    if (note) note.textContent = 'Сообщение скопировано. Вставьте его в открывшийся Telegram и отправьте.';
  });
}
